import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

import com.mytest.dvita.server.ConnectionManager;
import com.mytest.dvita.server.DVitaConfig;


public class InitializeConfigTables {

	/**
	 * @param args
	 */
	public static void main(String[] args) {
		if(args.length != 1 || !args[0].equals("UNDERSTOOD")) 
		{
			System.out.print(
				"NOTE: THIS WILL DROP ALL EXSITING CONFIG TABLES IN THE DATABASE,\n" +
				"SO PLEASE DO NOT RUN THIS COMMAND UNLESS YOU REALLY REALLY ARE SURE\n" +
				"THAT THERE ARE NO CONFIG_* TABLES IN THE DB SPECIFIED IN dvita.config\n\n" +
				"If you are damn sure you want to proceed, run this command again\n" +
				"and pass the argument UNDERSTOOD along");	
			return;
		}
		
		try {
			Connection c = ConnectionManager.getConnection();
			Statement statement = c.createStatement();

			String schema = DVitaConfig.getSchemaDot();

			Tools.DropTableIfExists(statement, "config_connection", schema);
			Tools.DropTableIfExists(statement, "config_rawdata", schema);
			Tools.DropTableIfExists(statement, "config_topicmining", schema);
			Tools.DropTableIfExists(statement, "config_gui", schema);
			Tools.DropTableIfExists(statement, "stopwords", schema);

			String sqltable = "CREATE TABLE "+ schema+ "config_connection ("
					+ "id integer NOT NULL,"
					+ "type integer NOT NULL,"
					+ "server varchar(100) NOT NULL,"
					+ "port integer NOT NULL,"
					+ "databasename varchar(50) NOT NULL,"
					+ "user varchar(100),"
					+ "password varchar(100),"
					+ "PRIMARY KEY (id)"
					+ ")";
			statement.executeUpdate(sqltable);

			sqltable = "CREATE TABLE " + schema + "config_rawdata ("
					+ "meta_title varchar(60) NOT NULL,"
					+ "meta_description varchar(200) NOT NULL,"
					+ "id integer NOT NULL UNIQUE,"
					+ "tablePrefix varchar(30) NOT NULL UNIQUE,"
					+ "columnNameID varchar(20) NOT NULL,"
					+ "columnNameDate varchar(20) NOT NULL,"
					+ "columnNameContent varchar(20) NOT NULL,"
					+ "columnNameTitle varchar(50) NOT NULL,"
					+ "columnNameURL varchar(50),"
					+ "columnNameCopyright varchar(50),"
					+ "columnNameTextDisplay varchar(50),"
					+ "columnNameAuthors varchar(50),"
					+ "from varchar(200) NOT NULL,"
					+ "where varchar(300),"
					+ "connectionID integer DEFAULT NULL,"
					+ "PRIMARY KEY (id),"
					+ "FOREIGN KEY (connectionID) REFERENCES "+ schema+ "config_connection(id)"
					+ ")";
			statement.executeUpdate(sqltable);

			sqltable = "CREATE TABLE "+ schema+ "config_topicmining ("
					+ "id integer NOT NULL UNIQUE,"
					+ "rawdataid integer NOT NULL,"
					+ "meta_title varchar(100) NOT NULL,"
					+ "meta_description varchar(200) NOT NULL,"
					+ "granularity integer NOT NULL,"
					+ "rangeStart timestamp NOT NULL,"
					+ "rangeEnd timestamp NOT NULL,"
					+ "tablePrefix varchar(30) NOT NULL UNIQUE,"
					+ "numberTopics integer NOT NULL,"
					+ "PRIMARY KEY (id),"
					+ "FOREIGN KEY (rawdataID) REFERENCES "+ schema+ "config_rawdata(id)"
					+ ")";
			statement.executeUpdate(sqltable);

			// tabelle gibt an, welche datenbanken/analyzen in der gui gezeigt werden
			// title, description = human understanable description
			// miningIDs (whitespace separated list of topicMiningIDs which should be grouped together in the GUI)
			sqltable = "CREATE TABLE "+ schema+ "config_gui ("
					+ "id integer NOT NULL,"
					+ "title varchar(100) NOT NULL,"
					+ "description varchar(200) NOT NULL,"
					+ "miningIDs varchar(200) NOT NULL,"
					+ "PRIMARY KEY (id)"	
					+ ")";
			statement.executeUpdate(sqltable);

			sqltable = "CREATE TABLE " + schema + "stopwords ("
					+"name varchar(16) NOT NULL,"
					+"lang char(2) DEFAULT 'en',"
					+"PRIMARY KEY(name)"
					+")";
			statement.executeUpdate(sqltable);

			String query = "INSERT INTO "+schema+"stopwords (name) VALUES"
					+ "('a'),"
					+ "('able'),"
					+ "('about'),"
					+ "('above'),"
					+ "('according'),"
					+ "('accordingly'),"
					+ "('across'),"
					+ "('actually'),"
					+ "('after'),"
					+ "('afterwards'),"
					+ "('again'),"
					+ "('against'),"
					+ "('all'),"
					+ "('allow'),"
					+ "('allows'),"
					+ "('almost'),"
					+ "('alone'),"
					+ "('along'),"
					+ "('already'),"
					+ "('also'),"
					+ "('although'),"
					+ "('always'),"
					+ "('am'),"
					+ "('among'),"
					+ "('amongst'),"
					+ "('an'),"
					+ "('and'),"
					+ "('another'),"
					+ "('any'),"
					+ "('anybody'),"
					+ "('anyhow'),"
					+ "('anyone'),"
					+ "('anything'),"
					+ "('anyway'),"
					+ "('anyways'),"
					+ "('anywhere'),"
					+ "('apart'),"
					+ "('appear'),"
					+ "('appreciate'),"
					+ "('appropriate'),"
					+ "('are'),"
					+ "('around'),"
					+ "('as'),"
					+ "('aside'),"
					+ "('ask'),"
					+ "('asking'),"
					+ "('associated'),"
					+ "('at'),"
					+ "('available'),"
					+ "('away'),"
					+ "('awfully'),"
					+ "('b'),"
					+ "('be'),"
					+ "('became'),"
					+ "('because'),"
					+ "('become'),"
					+ "('becomes'),"
					+ "('becoming'),"
					+ "('been'),"
					+ "('before'),"
					+ "('beforehand'),"
					+ "('behind'),"
					+ "('being'),"
					+ "('believe'),"
					+ "('below'),"
					+ "('beside'),"
					+ "('besides'),"
					+ "('best'),"
					+ "('better'),"
					+ "('between'),"
					+ "('beyond'),"
					+ "('both'),"
					+ "('brief'),"
					+ "('but'),"
					+ "('by'),"
					+ "('c'),"
					+ "('came'),"
					+ "('can'),"
					+ "('cannot'),"
					+ "('cant'),"
					+ "('cause'),"
					+ "('causes'),"
					+ "('certain'),"
					+ "('certainly'),"
					+ "('changes'),"
					+ "('clearly'),"
					+ "('co'),"
					+ "('com'),"
					+ "('come'),"
					+ "('comes'),"
					+ "('concerning'),"
					+ "('consequently'),"
					+ "('consider'),"
					+ "('considering'),"
					+ "('contain'),"
					+ "('containing'),"
					+ "('contains'),"
					+ "('corresponding'),"
					+ "('could'),"
					+ "('course'),"
					+ "('currently'),"
					+ "('d'),"
					+ "('definitely'),"
					+ "('described'),"
					+ "('despite'),"
					+ "('did'),"
					+ "('different'),"
					+ "('do'),"
					+ "('does'),"
					+ "('doing'),"
					+ "('done'),"
					+ "('down'),"
					+ "('downwards'),"
					+ "('during'),"
					+ "('e'),"
					+ "('each'),"
					+ "('edu'),"
					+ "('eg'),"
					+ "('eight'),"
					+ "('either'),"
					+ "('else'),"
					+ "('elsewhere'),"
					+ "('enough'),"
					+ "('entirely'),"
					+ "('especially'),"
					+ "('et'),"
					+ "('etc'),"
					+ "('even'),"
					+ "('ever'),"
					+ "('every'),"
					+ "('everybody'),"
					+ "('everyone'),"
					+ "('everything'),"
					+ "('everywhere'),"
					+ "('ex'),"
					+ "('exactly'),"
					+ "('example'),"
					+ "('except'),"
					+ "('f'),"
					+ "('far'),"
					+ "('few'),"
					+ "('fifth'),"
					+ "('first'),"
					+ "('five'),"
					+ "('followed'),"
					+ "('following'),"
					+ "('follows'),"
					+ "('for'),"
					+ "('former'),"
					+ "('formerly'),"
					+ "('forth'),"
					+ "('four'),"
					+ "('from'),"
					+ "('further'),"
					+ "('furthermore'),"
					+ "('g'),"
					+ "('get'),"
					+ "('gets'),"
					+ "('getting'),"
					+ "('given'),"
					+ "('gives'),"
					+ "('go'),"
					+ "('goes'),"
					+ "('going'),"
					+ "('gone'),"
					+ "('got'),"
					+ "('gotten'),"
					+ "('greetings'),"
					+ "('h'),"
					+ "('had'),"
					+ "('happens'),"
					+ "('hardly'),"
					+ "('has'),"
					+ "('have'),"
					+ "('having'),"
					+ "('he'),"
					+ "('hello'),"
					+ "('help'),"
					+ "('hence'),"
					+ "('her'),"
					+ "('here'),"
					+ "('hereafter'),"
					+ "('hereby'),"
					+ "('herein'),"
					+ "('hereupon'),"
					+ "('hers'),"
					+ "('herself'),"
					+ "('hi'),"
					+ "('him'),"
					+ "('himself'),"
					+ "('his'),"
					+ "('hither'),"
					+ "('hopefully'),"
					+ "('how'),"
					+ "('howbeit'),"
					+ "('however'),"
					+ "('i'),"
					+ "('ie'),"
					+ "('if'),"
					+ "('ignored'),"
					+ "('immediate'),"
					+ "('in'),"
					+ "('inasmuch'),"
					+ "('inc'),"
					+ "('indeed'),"
					+ "('indicate'),"
					+ "('indicated'),"
					+ "('indicates'),"
					+ "('inner'),"
					+ "('insofar'),"
					+ "('instead'),"
					+ "('into'),"
					+ "('inward'),"
					+ "('is'),"
					+ "('it'),"
					+ "('its'),"
					+ "('itself'),"
					+ "('j'),"
					+ "('just'),"
					+ "('k'),"
					+ "('keep'),"
					+ "('keeps'),"
					+ "('kept'),"
					+ "('know'),"
					+ "('known'),"
					+ "('knows'),"
					+ "('l'),"
					+ "('last'),"
					+ "('lately'),"
					+ "('later'),"
					+ "('latter'),"
					+ "('latterly'),"
					+ "('least'),"
					+ "('less'),"
					+ "('lest'),"
					+ "('let'),"
					+ "('like'),"
					+ "('liked'),"
					+ "('likely'),"
					+ "('little'),"
					+ "('look'),"
					+ "('looking'),"
					+ "('looks'),"
					+ "('ltd'),"
					+ "('m'),"
					+ "('mainly'),"
					+ "('many'),"
					+ "('may'),"
					+ "('maybe'),"
					+ "('me'),"
					+ "('mean'),"
					+ "('meanwhile'),"
					+ "('merely'),"
					+ "('might'),"
					+ "('more'),"
					+ "('moreover'),"
					+ "('most'),"
					+ "('mostly'),"
					+ "('much'),"
					+ "('must'),"
					+ "('my'),"
					+ "('myself'),"
					+ "('n'),"
					+ "('name'),"
					+ "('namely'),"
					+ "('nd'),"
					+ "('near'),"
					+ "('nearly'),"
					+ "('necessary'),"
					+ "('need'),"
					+ "('needs'),"
					+ "('neither'),"
					+ "('never'),"
					+ "('nevertheless'),"
					+ "('new'),"
					+ "('next'),"
					+ "('nine'),"
					+ "('no'),"
					+ "('nobody'),"
					+ "('non'),"
					+ "('none'),"
					+ "('noone'),"
					+ "('nor'),"
					+ "('normally'),"
					+ "('not'),"
					+ "('nothing'),"
					+ "('novel'),"
					+ "('now'),"
					+ "('nowhere'),"
					+ "('o'),"
					+ "('obviously'),"
					+ "('of'),"
					+ "('off'),"
					+ "('often'),"
					+ "('oh'),"
					+ "('ok'),"
					+ "('okay'),"
					+ "('old'),"
					+ "('on'),"
					+ "('once'),"
					+ "('one'),"
					+ "('ones'),"
					+ "('only'),"
					+ "('onto'),"
					+ "('or'),"
					+ "('other'),"
					+ "('others'),"
					+ "('otherwise'),"
					+ "('ought'),"
					+ "('our'),"
					+ "('ours'),"
					+ "('ourselves'),"
					+ "('out'),"
					+ "('outside'),"
					+ "('over'),"
					+ "('overall'),"
					+ "('own'),"
					+ "('p'),"
					+ "('particular'),"
					+ "('particularly'),"
					+ "('per'),"
					+ "('perhaps'),"
					+ "('placed'),"
					+ "('please'),"
					+ "('plus'),"
					+ "('possible'),"
					+ "('presumably'),"
					+ "('probably'),"
					+ "('provides'),"
					+ "('q'),"
					+ "('que'),"
					+ "('quite'),"
					+ "('qv'),"
					+ "('r'),"
					+ "('rather'),"
					+ "('rd'),"
					+ "('re'),"
					+ "('really'),"
					+ "('reasonably'),"
					+ "('regarding'),"
					+ "('regardless'),"
					+ "('regards'),"
					+ "('relatively'),"
					+ "('respectively'),"
					+ "('right'),"
					+ "('s'),"
					+ "('said'),"
					+ "('same'),"
					+ "('saw'),"
					+ "('say'),"
					+ "('saying'),"
					+ "('says'),"
					+ "('second'),"
					+ "('secondly'),"
					+ "('see'),"
					+ "('seeing'),"
					+ "('seem'),"
					+ "('seemed'),"
					+ "('seeming'),"
					+ "('seems'),"
					+ "('seen'),"
					+ "('self'),"
					+ "('selves'),"
					+ "('sensible'),"
					+ "('sent'),"
					+ "('serious'),"
					+ "('seriously'),"
					+ "('seven'),"
					+ "('several'),"
					+ "('shall'),"
					+ "('she'),"
					+ "('should'),"
					+ "('since'),"
					+ "('six'),"
					+ "('so'),"
					+ "('some'),"
					+ "('somebody'),"
					+ "('somehow'),"
					+ "('someone'),"
					+ "('something'),"
					+ "('sometime'),"
					+ "('sometimes'),"
					+ "('somewhat'),"
					+ "('somewhere'),"
					+ "('soon'),"
					+ "('sorry'),"
					+ "('specified'),"
					+ "('specify'),"
					+ "('specifying'),"
					+ "('still'),"
					+ "('sub'),"
					+ "('such'),"
					+ "('such as'),"
					+ "('sup'),"
					+ "('sure'),"
					+ "('t'),"
					+ "('take'),"
					+ "('taken'),"
					+ "('tell'),"
					+ "('tends'),"
					+ "('th'),"
					+ "('than'),"
					+ "('thank'),"
					+ "('thanks'),"
					+ "('thanx'),"
					+ "('that'),"
					+ "('thats'),"
					+ "('the'),"
					+ "('their'),"
					+ "('theirs'),"
					+ "('them'),"
					+ "('themselves'),"
					+ "('then'),"
					+ "('thence'),"
					+ "('there'),"
					+ "('thereafter'),"
					+ "('thereby'),"
					+ "('therefore'),"
					+ "('therein'),"
					+ "('theres'),"
					+ "('thereupon'),"
					+ "('these'),"
					+ "('they'),"
					+ "('think'),"
					+ "('third'),"
					+ "('this'),"
					+ "('thorough'),"
					+ "('thoroughly'),"
					+ "('those'),"
					+ "('though'),"
					+ "('three'),"
					+ "('through'),"
					+ "('throughout'),"
					+ "('thru'),"
					+ "('thus'),"
					+ "('to'),"
					+ "('together'),"
					+ "('too'),"
					+ "('took'),"
					+ "('toward'),"
					+ "('towards'),"
					+ "('tried'),"
					+ "('tries'),"
					+ "('truly'),"
					+ "('try'),"
					+ "('trying'),"
					+ "('twice'),"
					+ "('two'),"
					+ "('u'),"
					+ "('un'),"
					+ "('under'),"
					+ "('unfortunately'),"
					+ "('unless'),"
					+ "('unlikely'),"
					+ "('until'),"
					+ "('unto'),"
					+ "('up'),"
					+ "('upon'),"
					+ "('us'),"
					+ "('use'),"
					+ "('used'),"
					+ "('useful'),"
					+ "('uses'),"
					+ "('using'),"
					+ "('usually'),"
					+ "('uucp'),"
					+ "('v'),"
					+ "('value'),"
					+ "('various'),"
					+ "('very'),"
					+ "('via'),"
					+ "('viz'),"
					+ "('vs'),"
					+ "('w'),"
					+ "('want'),"
					+ "('wants'),"
					+ "('was'),"
					+ "('way'),"
					+ "('we'),"
					+ "('welcome'),"
					+ "('well'),"
					+ "('went'),"
					+ "('were'),"
					+ "('what'),"
					+ "('whatever'),"
					+ "('when'),"
					+ "('whence'),"
					+ "('whenever'),"
					+ "('where'),"
					+ "('whereafter'),"
					+ "('whereas'),"
					+ "('whereby'),"
					+ "('wherein'),"
					+ "('whereupon'),"
					+ "('wherever'),"
					+ "('whether'),"
					+ "('which'),"
					+ "('while'),"
					+ "('whither'),"
					+ "('who'),"
					+ "('whoever'),"
					+ "('whole'),"
					+ "('whom'),"
					+ "('whose'),"
					+ "('why'),"
					+ "('will'),"
					+ "('willing'),"
					+ "('wish'),"
					+ "('with'),"
					+ "('within'),"
					+ "('without'),"
					+ "('wonder'),"
					+ "('would'),"
					+ "('x'),"
					+ "('y'),"
					+ "('yes'),"
					+ "('yet'),"
					+ "('you'),"
					+ "('your'),"
					+ "('yours'),"
					+ "('yourself'),"
					+ "('yourselves'),"
					+ "('z'),"
					+ "('zero')";

			statement.executeUpdate(query);

			c.close();
		} 
		catch (SQLException e) 
		{
			e.printStackTrace();
		}
	}
}
